# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        
    - name: Test
      run: make test
  
  publish: # this step only run on push to main branch
    needs: test
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    
    - name: Create tag
      run: make push-tag

    - name: Publish
      run: make publish-version

    - name: Bump version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make echo-version bump-version .ci-helper-git-config-user
        [ $? -eq 0 ] && make .ci-helper-gh-bump-version-commit-with-pr
        [ $? -eq 0 ] && make .ci-helper-gh-auto-merge-pr-of-branch GH_BRANCH=`cat .ci-helper-gh-bump-version-commit-with-pr`
        
